/**
 * The board, as text you can commit.
 *
 * A diagram inside a desktop app helps whoever has the app open. A Mermaid block in the README
 * helps the person who arrives in eight months, and GitHub renders it without anyone installing
 * anything. So the same graph Notch draws is emitted as source — same nodes, same edges, same
 * distinction between what exists and what is missing.
 *
 * WHAT SURVIVES THE TRANSLATION MATTERS MORE THAN WHAT IT LOOKS LIKE. A missing service is
 * still drawn, still dashed, and still labelled with the import that proves the code wants it.
 * A picture that quietly dropped the gaps would be a nicer diagram and a worse document.
 */
import type { ArchNode } from './graph.js';

export interface WiringEdgeLike {
  to: string;
  found: string;
  confidence: string;
  deployed: boolean;
}

export interface MermaidInput {
  projectName: string;
  nodes: readonly ArchNode[];
  /** Types the code needs that the project has not got. */
  missing: readonly string[];
  runtime: string | null;
  edges: readonly WiringEdgeLike[];
  repo: { name: string; satisfied: number; missing: number } | null;
}

/**
 * Mermaid ids must be bare words. Anything else — a dot, a dash, a space — ends the token and
 * the diagram fails to parse with an error that points at the wrong line.
 */
const id = (s: string): string => {
  const safe = s.replace(/[^A-Za-z0-9]/g, '_').replace(/^(\d)/, 'n$1');
  return safe === '' ? 'n' : safe;
};

/** `"` and newlines terminate a Mermaid label. Both appear in real service names. */
const label = (s: string): string => s.replace(/["\n]/g, ' ').trim();

export function toMermaid(input: MermaidInput): string {
  const { projectName, nodes, missing, runtime, edges, repo } = input;
  const out: string[] = [];

  out.push(`%% ${label(projectName)} — generated by Notch from the live Zerops account.`);
  out.push('%% Dashed nodes are services this repository needs and the project does not have.');
  out.push('flowchart LR');

  if (repo !== null) {
    out.push(`  ${id('repo')}["${label(repo.name)}<br/><small>${repo.satisfied} satisfied · ${repo.missing} missing</small>"]`);
  }

  const runtimeNode = nodes.find((n) => n.kind === 'runtime');
  const anchor = runtimeNode === undefined ? null : id(`s_${runtimeNode.name}`);

  out.push(`  subgraph ${id(projectName)}["${label(projectName)}"]`);
  for (const n of nodes) {
    out.push(`    ${id(`s_${n.name}`)}["${label(n.name)}<br/><small>${label(n.typeName)}</small>"]`);
  }
  for (const m of missing) {
    out.push(`    ${id(`g_${m}`)}["${label(m)}<br/><small>missing</small>"]`);
  }
  out.push('  end');

  if (repo !== null && anchor !== null) {
    out.push(`  ${id('repo')} -->|scanned| ${anchor}`);
  }

  if (anchor !== null) {
    for (const e of edges) {
      const target = nodes.some((n) => n.typeName.toLowerCase().replace(/[^a-z0-9]/g, '').includes(e.to))
        ? id(`s_${nodes.find((n) => n.typeName.toLowerCase().replace(/[^a-z0-9]/g, '').includes(e.to))?.name ?? e.to}`)
        : missing.includes(e.to) ? id(`g_${e.to}`) : null;
      if (target === null || target === anchor) continue;
      /*
       * The edge label is QUOTED, and it has to be.
       *
       * An unquoted `@aws-sdk/client-s3` does not parse: Mermaid reads the `@` as the start of
       * a link id and fails with "Expecting AMP, COLON, PIPE… got LINK_ID". Every label here is
       * an npm package name straight out of somebody's package.json, so scoped packages are the
       * common case rather than the exotic one — and the first real export of this feature
       * produced a diagram that rendered as GitHub's error box.
       *
       * `-.->` for a connection the code makes that the platform has not been told about.
       */
      out.push(`  ${anchor} ${e.deployed ? '-->' : '-.->'}|"${label(e.found)}"| ${target}`);
    }
  }

  // Styling last, so the graph parses even if a renderer ignores classDef.
  out.push('  classDef missing stroke-dasharray: 5 4,stroke:#ef4444,color:#ef4444,fill:transparent;');
  if (missing.length > 0) {
    out.push(`  class ${missing.map((m) => id(`g_${m}`)).join(',')} missing;`);
  }
  if (runtime !== null && anchor !== null) {
    out.push('  classDef runtime stroke:#a78bfa,stroke-width:2px;');
    out.push(`  class ${anchor} runtime;`);
  }

  return out.join('\n') + '\n';
}
